# Site settings
title: "Ožbolt Menegatti"
email: site@ozbo.lt
email_scrambled: siteREMOVEME@ozbo.lt
description: "Father - Engineer - Sportsman - Pacifist - Chess enthusiast."
baseurl: ""
url: "https://ozbo.lt/"
title_description: "Father - Engineer - Sportsman - Pacifist - Chess enthusiast"
title_image: "/static/svica_jst.jpg"
github_repository: https://github.com/gareins/gareins.github.io
post_limit: 5

github_username:  gareins
linkedin_link: https://si.linkedin.com/in/o%C5%BEbolt-menegatti-a2306a71
stackoverflow_link: https://stackoverflow.com/users/1255969
facebook_link: https://facebook.com/ozbolt.menegatti
gitlab_username: gareins
chess_link: https://lichess.org/@/gareins

# Build settings
markdown: kramdown
sass: 
    sass_dir: css

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
